version: '3.8'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_USERNAME=admin
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE_DATABASE=mydb
    ports: 
      - '27017:27017'